"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useParams} from "next/navigation";import {ArrowLeft,Building2,CreditCard,MonitorPlay,Sparkles} from "lucide-react";import {createClient} from "@/lib/supabase/client";
export default function CustomerDetail(){const {id}=useParams<{id:string}>();const [data,setData]=useState<any>(null);const [error,setError]=useState<string|null>(null);const [credit,setCredit]=useState(10);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);
useEffect(()=>{let on=true;(async()=>{const s=createClient();const [o,sub,orders,credits,screens]=await Promise.all([s.from("organizations").select("id,name,plan,trial_ends_at,created_at").eq("id",id).single(),s.from("subscriptions").select("*").eq("organization_id",id).maybeSingle(),s.from("billing_orders").select("id,plan,billing_period,amount_cents,currency,status,created_at").eq("organization_id",id).order("created_at",{ascending:false}).limit(20),s.from("credit_ledger").select("id,amount,reason,created_at").eq("organization_id",id).order("created_at",{ascending:false}).limit(50),s.from("screens").select("id,name,location,width,height,device_status,last_seen_at").eq("organization_id",id).order("created_at",{ascending:false})]);if(!on)return;const e=o.error||sub.error||orders.error||credits.error||screens.error;if(e){setError(e.message);return}setData({org:o.data,sub:sub.data,orders:orders.data||[],credits:credits.data||[],screens:screens.data||[]})})();return()=>{on=false}},[id]);
if(!data)return <main className="min-h-screen bg-[#07090d] p-8 text-white">{error||"Yükleniyor..."}</main>;
const balance=data.credits.reduce((a:number,x:any)=>a+Number(x.amount||0),0);\nasync function grantCredit(){setSaving(true);setMessage(null);const r=await fetch("/api/admin/credits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:id,amount:credit})});const j=await r.json();if(!r.ok){setMessage(j.error||"İşlem başarısız.");setSaving(false);return}setData((d:any)=>({...d,credits:[{id:crypto.randomUUID(),amount:credit,reason:"admin_grant",created_at:new Date().toISOString()},...d.credits]}));setMessage(`${credit} kredi eklendi.`);setSaving(false)}
return <main className="min-h-screen bg-[#07090d] p-5 text-white sm:p-8"><div className="mx-auto max-w-6xl"><Link href="/yonetim/musteriler" className="flex items-center gap-2 text-sm text-zinc-400"><ArrowLeft size={16}/>Müşterilere dön</Link><div className="mt-7 flex items-center gap-3"><Building2 className="text-cyan-300"/><div><h1 className="text-3xl font-semibold">{data.org.name}</h1><p className="mt-1 text-sm text-zinc-500">Müşteri / şirket kontrol merkezi</p></div></div>
<div className="mt-7 grid gap-4 sm:grid-cols-3"><Card icon={CreditCard} title="Paket" value={data.sub?.plan||data.org.plan}/><Card icon={Sparkles} title="Kredi" value={balance}/><Card icon={MonitorPlay} title="LED Ekran" value={data.screens.length}/></div>
<section className="mt-7 rounded-2xl border border-cyan-400/15 bg-[#0c0f14] p-5"><h2 className="font-semibold">Yönetici İşlemleri</h2><p className="mt-1 text-sm text-zinc-500">Bu müşterinin AI video kredi bakiyesine güvenli şekilde kredi ekleyin.</p><div className="mt-4 flex max-w-md gap-2"><input type="number" min={1} max={100000} value={credit} onChange={e=>setCredit(Number(e.target.value))} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-cyan-400/40"/><button onClick={grantCredit} disabled={saving||credit<1} className="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-black disabled:opacity-50">{saving?"Ekleniyor...":"Kredi Ekle"}</button></div>{message&&<p className="mt-3 text-sm text-cyan-300">{message}</p>}</section>\n<section className="mt-4 rounded-2xl border border-white/[.07] bg-[#0c0f14] p-5"><h2 className="font-semibold">Ödemeler</h2><div className="mt-3 space-y-2">{data.orders.length?data.orders.map((x:any)=><div key={x.id} className="flex justify-between border-t border-white/[.06] py-3 text-sm"><span className="capitalize">{x.plan} · {x.billing_period}</span><span>{(x.amount_cents/100).toLocaleString("tr-TR")} {x.currency} · {x.status}</span></div>):<p className="text-sm text-zinc-500">Ödeme kaydı yok.</p>}</div></section>
<section className="mt-4 rounded-2xl border border-white/[.07] bg-[#0c0f14] p-5"><h2 className="font-semibold">LED Ekranlar</h2><div className="mt-3 space-y-2">{data.screens.length?data.screens.map((x:any)=><div key={x.id} className="flex justify-between border-t border-white/[.06] py-3 text-sm"><span>{x.name} · {x.location||"-"}</span><span className="text-zinc-400">{x.width}×{x.height} · {x.device_status||"offline"}</span></div>):<p className="text-sm text-zinc-500">Ekran bulunmuyor.</p>}</div></section>
</div></main>}
function Card({icon:I,title,value}:{icon:any,title:string,value:any}){return <div className="rounded-2xl border border-white/[.07] bg-[#0c0f14] p-5"><I className="text-cyan-300"/><p className="mt-4 text-xs text-zinc-500">{title}</p><p className="mt-1 text-2xl font-semibold capitalize">{value}</p></div>}
